apiVersion: v1
kind: Pod
metadata:
  name: violating-kyverno-policy-label
  labels: 
    app: violating-kyverno-policy-label
spec:
  containers:
  - image: curlimages/curl
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: connecting-pod
  restartPolicy: Always