apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: first-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-csi # this is azures standard storageclass, on our private cloud you will have different names