apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: declarative-deploy
  name: declarative-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: declarative-deploy
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: declarative-deploy
    spec:
      containers:
      - image: "syseleven/metakube-hello:2.0.0"
        name: nginx
