apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: sample-simple
  # This namespace is special and auto-wired to deploy to the local cluster
  namespace: fleet-local
spec:
  # Everything from this repo will be run in this cluster. You trust me right?
  repo: "https://github.com/localleon/kubernetes-workshop-module"
  branch: main
  # or
  # repo: "ssh://git@github.com/rancher/fleet-examples"
  paths:
  - kubernetes-modules/12-gitops-fleet/simple

  targetNamespace: fleet-sample-simple