apiVersion: v1
kind: Namespace
metadata:
  name: cloudnativepg
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudnative-pg-charts
  namespace: flux-system
spec:
  interval: "1h"
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnativepg
  namespace: cloudnativepg
spec:
  releaseName: cnpg 
  chart:
    spec:
      chart: cloudnative-pg
      # version: '16.4.6'
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg-charts
        namespace: flux-system
  interval: 50m
  values:
  # Add your helm-values of chart here