apiVersion: v1
kind: Namespace
metadata:
  name: coder
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami-oci
  namespace: flux-system
spec:
  interval: "1h"
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder-db
  namespace: coder
spec:
  releaseName: coder-db
  chart:
    spec:
      chart: postgressql
      version: '16.4.6'
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: flux-system
  interval: 50m
  values:
  # Add your helm-values of chart here
    global: 
      postgresql: 
        auth: 
          username: coder 
          password: coder # Since these are temporary and not accessible services, hardcoding is fine for development
          database: coder 
    primary: 
      persistence: 
        size: 10Gi
        storageClass: managed-csi # Create a azure disk
--- 
apiVersion: v1
kind: Secret
metadata:
  name: coder-db-url
  namespace: coder
type: generic
stringData:
  url: "postgres://coder:coder@coder-db-postgresql.coder.svc.cluster.local:5432/coder?sslmode=disable"
