apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubernetes-sig-external-dns
  namespace: flux-system
spec:
  interval: "1h"
  url: https://kubernetes-sigs.github.io/external-dns/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  releaseName: external-dns 
  chart:
    spec:
      chart: external-dns
      version: '1.15.2'
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sig-external-dns
        namespace: flux-system
  interval: 50m
  # Add your helm-values of chart here
  values:
    # Settings for workload identity 
    serviceAccount:
      labels:
        azure.workload.identity/use: "true"
      annotations:
        azure.workload.identity/client-id: 0690c01b-22f4-490d-87af-a362ad3e0682

    podLabels:
      azure.workload.identity/use: "true"

    extraVolumes:
      - name: azure-config-file
        secret:
          secretName: external-dns-azure

    extraVolumeMounts:
      - name: azure-config-file
        mountPath: /etc/kubernetes
        readOnly: true

    # Settings for domain listening 
    provider:
      name: azure

    # Kubernetes_ resources to monitor for DNS entries.
    sources:
      - ingress
    # -- Limit possible target zones by domain suffixes.
    domainFilters: 
      - aks-dev0.amp-cloud.net

    # -- Extra arguments to provide to _ExternalDNS_.
    extraArgs: 
      - --azure-resource-group=rg-lraus-k8sdev