FROM registry.access.redhat.com/ubi9 AS build
RUN dnf update -y
RUN dnf install java-17-openjdk-devel -y
WORKDIR /app
COPY HelloWorld.java .
RUN javac HelloWorld.java
RUN jar cfe app.jar HelloWorld HelloWorld.class
RUN ls -lha

FROM gcr.io/distroless/java17-debian12
COPY --from=build /app/app.jar /app/app.jar
WORKDIR /app
CMD ["app.jar"]