apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: infra/fluxcd-apps
  prune: true
  wait: true
--- 
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: workshop
  namespace: flux-system
spec:
  dependsOn:
    - name: apps # Wait till base infrastructure apps are deployed 
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: infra/fluxcd-workshop
  prune: true
  wait: true
--- 