apiVersion: v1
kind: Namespace
metadata:
  name: coderdb
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: coderdb
  namespace: coderdb
spec:
  instances: 1
  enablePDB: false # since we do not wan#t to block draining of cluster with only one db instance
  storage:
    storageClass: managed-csi
    size: 10Gi
  # Create CoderDB
  bootstrap:
    initdb:
      database: coder
      owner: coder