FROM registry.access.redhat.com/ubi9-minimal
RUN microdnf update -y
RUN microdnf install java-17-openjdk-devel -y

RUN java -version && javac -version

WORKDIR /app

COPY HelloWorld.java .

RUN javac HelloWorld.java

CMD ["java","HelloWorld"]